### ISSUE TITLE
Squished buttons with tiny icons in Storage list

### ISSUE THREAD

**Issue by lepa22** [AstraExt/astra-monitor#45] opened 2024-01-29 15:19 UTC
## Description
The buttons at the bottom of the _Storage_ item have a squished shape and the icons in them are scaled down, making them extremely hard to see. This may be a result of the increased length of the _Storage_ item list since the addition of the _Top processes_ section.

## Steps to Reproduce
1. Install and enable the extension.
2. Click the _Storage_ item on the top bar.
3. The buttons at the bottom of the list are squished and the icons are tiny.

## Screenshots
![image](https://github.com/AstraExt/astra-monitor/assets/16370046/dfa87b30-9e09-4e73-974b-4d5f4d5c844c)

## Environment
- **Astra Monitor Version**: 9 (EGOv13)
- **GNOME Version**: 45.3
- **Operating System and Version**: Fedora 39 Workstation

**Comment by ljuzig** [comment] 2024-02-02 15:48
I'm not able to reproduce that. Do you still have this bug?

**Comment by lepa22** [comment] 2024-02-02 16:17
Yes, even with the TypeScript testing version. I only see this issue on the _Storage_ item list, which occupies the whole vertical length of my screen. The other items are not as long, so that's why I suspect it's an issue with the list's length.

Do you have any item list as long? If not, maybe you can reproduce the bug by artificially creating a long item list.

Of course I'll be happy to share more information if you tell me what I can do to get that!

**Comment by ljuzig** [comment] 2024-02-02 17:32
Ok, now I reproduced the bug. We don't actually have a way to properly display many items with a scrolling bar for example. For now I can add a setting like for the networks to manually hide some storage selecting them or with a regex.

**Comment by lepa22** [comment] 2024-02-02 17:47
Understandable. Perhaps a check box list presenting all the drives to the user would be nice for this. Then the user could select all the drives/partitions that they would like to monitor. However, the issue of the squished buttons could still occur if the user selects many drives/partitions.

As a more proper solution, and since all drives/partitions have the same height, would it be possible for a calculation to be made and adapt the list to fit the user's monitor? For example by hiding the last `n` entries if the list's length exceeds the monitor's effective height?

**Comment by ljuzig** [comment] 2024-02-02 18:21
Done:
![Screenshot from 2024-02-02 19-15-04](https://github.com/AstraExt/astra-monitor/assets/11982322/e3741cd4-a6d0-42c8-8845-ff3a1bec3040)

The additional solution you proposed will be integrated into menu customization in a future version, which is currently absent. However, I have a wide range of customizations listed for what is shown in the menus and even in what order that will eventually be implemented in the future.

**Closed** 2024-02-02 18:22 UTC
Labels: bug

**Comment by lepa22** [comment] 2024-02-02 21:02
I just tested the latest changes and ignoring partitions works properly! However, now the bars showing how full the devices are appear empty (see screenshot). Since these changes are not yet in a released version, I'm not sure if I should report this as a new bug, thus I'm mentioning it here.

![image](https://github.com/AstraExt/astra-monitor/assets/16370046/d2419c05-a2ca-42e5-8dad-1f74e2a0cc9c)

**Comment by ljuzig** [comment] 2024-02-02 22:11
Wow, very good catch. This is actually a bug introduced by the fix for #50. Gonna fix that right now!

**Comment by lepa22** [comment] 2024-02-02 22:42
Just tested. All is well!
