### ISSUE TITLE
IO Speeds overflow the status bar

### ISSUE THREAD

**Issue by ridiekel** [AstraExt/astra-monitor#112] opened 2024-04-21 09:16 UTC
## Description

When showing the disk IO Speed or Network IO Speed, the numbers overflow the status bar. You can see an example in the screenshot below. The font size also seems to randomly change depending on the data shown in the IO speed.

It suspect (fractional?) scaling might be involved, since I only have it when I scale my monitor.

## Steps to Reproduce

1. Enable IO Speed of either Network or Disk.
2. Scale monitor

## Screenshots

![image](https://github.com/AstraExt/astra-monitor/assets/2812109/02d030cc-6870-4146-b7ce-2bd82f60d3a8)

## Environment

-   **Astra Monitor Version**: 19 (EGOv30)
-   **GNOME Version**: 46
-   **Operating System and Version**: Ubuntu 24.04 and Ubuntu 23.10
-   **Other Relevant System Information**: Don't know what would be relevant.

## Logs

N/A

## Additional Context

N/A

**Comment by fedkad** [comment] 2024-04-21 10:00
What is your screen resolution? Are you using scaling other than 100%?

**Comment by ljuzig** [comment] 2024-04-21 10:02
Duplicate of #110. I'm waiting EGO to approve the update.

**Closed** 2024-04-21 10:02 UTC
Labels: bug
