### ISSUE TITLE
`CPU Core Usage Info` ignores main color

### ISSUE THREAD

**Issue by zeerayne** [AstraExt/astra-monitor#90] opened 2024-03-23 17:32 UTC
## Description
`CPU Core Usage Info` ignores main color, so user load is shown as transparent/blank when `Core Bars Breakdown` setting is ON.

## Steps to Reproduce
1. Apply some user load to CPU
2. Hover cursor over breakdown
3. That's it, you'll see missing main color in `CPU Core Usage Info`

## Screenshots
![image](https://github.com/AstraExt/astra-monitor/assets/13994839/8a6a3cf9-a8d5-4558-8dcb-69a5b77a4605)
![image](https://github.com/AstraExt/astra-monitor/assets/13994839/920e4453-a5fc-4462-bda6-c60cfaf77264)

## Environment
- **Astra Monitor Version**: 15
- **GNOME Version**: 45.5
- **Operating System and Version**: Arch Linux

**Comment by ljuzig** [comment] 2024-03-23 20:36
Thank you for reporting. This is duplicate of #86 and it has already been fixed, waiting for the next release.

**Closed by ljuzig** 2024-03-23 20:36 UTC
Labels: bug
