### ISSUE TITLE
GPU stats only updating when GPU is used?

### ISSUE THREAD

**Issue by l3ifk** [AstraExt/astra-monitor#136] opened 2024-07-26 11:31 UTC
It seems like the gpu graph and also the dropdown menu freeze every time I stop using my GPU, e.g. closing a game. Whenever I use it again, the graph updates and is working again.
Is this intended behavior to not ping the GPU and waste energy consumption or is this not inteded? 
Would be interesting to know...

**Comment by ljuzig** [comment] 2024-07-26 14:48
I'm not experiencing this issue. Can you help me naming some game and steps to reproduce it or provide a video? Thanks.

**Comment by l3ifk** [comment] 2024-07-26 15:23
As you can see [here](https://imgur.com/0tErNys) the GPU stats are monitored if it is utilized by the game and the stats freeze when I close the game. This is not specific to one game, but happens every time when the GPU is not utilized any more. Maybe it has to do something with me having a Laptop and therefore using the iGPU most of the time and only the dedicated GPU for more intense tasks?

**Comment by ljuzig** [comment] 2024-07-26 16:10
I guess it happens when switching from the dedicated GPU to the integrated one. I don't have a configuration where I can test that right now, I need to find a way to test it.

**Comment by l3ifk** [comment] 2024-07-26 18:33
Maybe a solution could be to give the option to show graphs of more than one GPU in the topbar. That way I would see when the system switches to my iGPU and vice versa. I don't know how hard it is to implement but I think it would be helpful.

**Comment by veldenb** [comment] 2024-09-30 13:48
I think this is resolved here: https://github.com/AstraExt/astra-monitor/issues/150

**Comment by ljuzig** [comment] 2024-09-30 14:17
@veldenb most likely that was the cause. Gonna close this too, thank you!

**Closed by ljuzig** 2024-09-30 14:17 UTC
Labels: bug
