### ISSUE TITLE
Text visibility

### ISSUE THREAD

**Issue by cybbro** [AstraExt/astra-monitor#3] opened 2024-01-12 08:52 UTC
## Description
First of all, amazing extension! Absolutely love it, but I want to ask, is it possible to make text more readable in the top bar? It appears grey - super hard to read the data.

![image](https://github.com/AstraExt/astra-monitor/assets/10908092/0c580d98-7388-4e3c-8be6-f522e952cf8c)

Text is grey, barely visible for download/upload speed, also CPU, GPU temperatures.

![image](https://github.com/AstraExt/astra-monitor/assets/10908092/fdabab2a-0c82-46b9-b30c-38f0107266a5)

## Environment

- **Astra Monitor Version**: 3
- **GNOME Version**: 45.2
- **Operating System and Version**: Ubuntu 23.10
- **Other Relevant System Information**:

**Comment by ljuzig** [comment] 2024-01-12 20:33
Thank you for your kind words. I actually don't change the font, the extension uses the default font of the system. I would like to add more customization options in the next version, including icons and colors. Font customization could be added on the list (style, color, size, etc.). I'm not really sure how much will it take to add a full customization option for text and fonts, but I will try to make it fit for the next release. I will keep you updated.

**Comment by fedkad** [comment] 2024-01-15 16:18
My problem may be related to this.

I had setup **Show IO Speed** in **Network** and **Storage**. Initially they worked fine: Two lines for each speed and they were very readable.

After restart, however, they are messed up:

![image](https://github.com/AstraExt/astra-monitor/assets/113997707/069bd847-5f86-45a0-954e-3c6719d98ca0)

I tried to toggle the **Show IO Speed** switches several times, nothing changed; the problem persists.

**Comment by fedkad** [comment] 2024-01-16 09:49
> That's a very interesting bug, but unrelated with OP. It's not easy to adapt settings in real time, many extensions require a restart after this kind of changes. It's hard for me to fix that without a clear way on how to reproduce it. How often does it occur?

It seems that this problem repeated after each login. However, I am using the **Dash to Panel** GNOME extension and it may be the cause (not 100% sure though). When I disable **Dash to Panel** the problem sometimes is fixed, but sometimes is not. When I enable it, then the problem repeats itself almost always. 

Disabling **Astra Monitor** and re-enabling it seems to solve the problem (always?).

**Comment by ljuzig** [comment] 2024-01-16 10:07
@fedkad There is no line terminator, they are two different labels in a BoxLayout so that should never occur. I made a blind attempt of fixing that in the next release. If that persists open a new issue so I can keep track of that cuz I'm gonna close this one soon for implementing what OP asked for.

**Closed** 2024-01-16 10:13 UTC
Labels: bug, enhancement
